# Generated by Django 4.0.2 on 2022-06-26 13:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, default='www.instagram.com/', help_text='Instagram URL', max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, default='www.facebook.com/', help_text='Facebook URL', max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, default='www.twitter.com/', help_text='Twitter URL', max_length=100, null=True)),
                ('pinterest', models.URLField(blank=True, default='www.pinterest.com/', help_text='Pinterest URL', max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, default='www.linkedin.com/', help_text='Linkedin URL', max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, default='Enter your WhatsApp number', help_text='Whatsapp Number', max_length=100, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Channel',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Your website name', max_length=100, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('show_in_menu_bar', models.BooleanField(blank=True, default=False, help_text='Select to show logo in menu bar', verbose_name='Menu Logo')),
                ('show_title_in_menu_bar', models.BooleanField(blank=True, default=False, help_text='Select to show Title in menu bar', verbose_name='Menu Title')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_logo', models.ForeignKey(blank=True, help_text='Your website logo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Setting',
            },
        ),
        migrations.CreateModel(
            name='HourSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_and_date', wagtail.core.fields.RichTextField(blank=True, verbose_name='Time and Day')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Hours Setting',
            },
        ),
        migrations.CreateModel(
            name='GoogleMapSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='The API Key used for Google Maps', max_length=100, null=True, verbose_name='Google Maps API Key')),
                ('map_title', models.CharField(blank=True, help_text='Map Title for Screen readers, ex: Map to Goodale Park', max_length=100, null=True, verbose_name='Map TitleGoogle Place ID')),
                ('place_id', models.CharField(blank=True, help_text='Requires API Key to use place ID', max_length=100, null=True, verbose_name='')),
                ('map_zoom_level', models.IntegerField(blank=True, help_text='Requires API Key to use zoom. 1: World, 5: Landmass/Continent, 10: City, 15: Streets, 20: Buildings', null=True, verbose_name='Map zoom level')),
                ('search', models.CharField(blank=True, help_text='Address or search term used to find your location on the map', max_length=250, verbose_name='Search')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Google Map Setting',
            },
        ),
        migrations.CreateModel(
            name='AdmissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Admission Setting',
            },
        ),
        migrations.CreateModel(
            name='AddressSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', wagtail.core.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Address Setting',
            },
        ),
    ]
