# Generated by Django 4.0.2 on 2022-06-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresssetting',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='admissionsetting',
            name='title',
            field=models.CharField(blank=True, default='Admission', max_length=100, null=True),
        ),
    ]
