# Generated by Django 4.0.2 on 2022-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_addresssetting_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresssetting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='googlemapsetting',
            name='map_title',
            field=models.CharField(blank=True, help_text='Map Title for Screen readers, ex: Map to Goodale Park', max_length=100, null=True, verbose_name='Map Title'),
        ),
        migrations.AlterField(
            model_name='googlemapsetting',
            name='place_id',
            field=models.CharField(blank=True, help_text='Requires API Key to use place ID', max_length=100, null=True, verbose_name='Google Place ID'),
        ),
    ]
