# Generated by Django 4.0.2 on 2022-06-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_addresssetting_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='title',
            field=models.CharField(blank=True, default='Join Us on', help_text='Title', max_length=100, null=True),
        ),
    ]
